apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: course-nfs-storage
provisioner: fuseim.pri/ifs
reclaimPolicy: Retain  
allowVolumeExpansion: true
#reclaimPolicy: Delete
#volumeBindingMode: WaitForFirstConsumer  
volumeBindingMode: Immediate  
