---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-pg  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: k8s-pg  
  labels: 
    app: postgres-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: k8s-pg
spec:
  serviceName: postgres
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  updateStrategy:
    type: RollingUpdate      
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "hzhy1234"
        #- name: POSTGRES_DB
        #  value: "hzhy"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      storageClassName: "course-nfs-storage"    
