apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-gateway
  namespace: k8s-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-gateway
  template:
    metadata:
      labels:
        app: mcp-gateway
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: mcp-gateway
        image:  huizhizhinengoso/mcp-gateway-server:v2.1.0.20250612-Release
        imagePullPolicy: IfNotPresent
        env:
        - name: EtcdHosts
          value: "etcd-svc:2379"
        - name: RedisHost
          value: "redis-svc:6379"
        - name: RedisType
          value: "node"
        - name: RedisPass 
          value: "password"
        - name: Port
          value: "8888"
        - name: Timeout
          value: "10000"