apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-validation
  namespace: k8s-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-validation
  template:
    metadata:
      labels:
        app: mcp-validation
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-node2
      containers:
      - name: mcp-validation
        image:  huizhizhinengoso/mcp-validation-server:v2.1.0.20250612-Release
        imagePullPolicy: IfNotPresent
        env:
        - name: EtcdHosts
          value: "etcd-svc:2379"
        - name: RedisHost
          value: "redis-svc:6379"
        - name: RedisType
          value: "node"
        - name: RedisPass 
          value: "password"
        - name: ListenOn
          value: "0.0.0.0:8081"        